# Generated by Django 4.2.4 on 2023-09-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilluponline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
