# Generated by Django 4.2.4 on 2023-09-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilluponline', '0002_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
