# Generated by Django 4.2.4 on 2023-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilluponline', '0009_alter_lesson_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('handle', 'handle'), ('done', 'done'), ('canceled', 'canceled')], default='new', max_length=20),
        ),
    ]
